apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: dmz-pool
  namespace: metallb-system
spec:
  addresses:
  - 100.100.100.10-100.100.100.100
  autoAssign: false
  avoidBuggyIPs: true
